Class'Code wordpress plugin PHP/JS middleware: OpenClassroomsAPI Class Reference
OpenClassroomsAPI Class Reference
Defines the functionnalities to acces to the OpenClassroooms API.
Public Member Functions
getUserLearningActivity ($update=true, $as_string=false)
Gets the OpenClassroooms user learning activity for the registered courses.
getAccessToken ()
Encapsulates a OAuth2 token request.
clearAccessToken ()
Clears the OAuth2 data in order to restart an authentification.
do_token_request ($request)
Implements the hook to manage redirection URL during OAuth2 token request.
userData ($name, $value=false, $clear=false)
Gets/Sets the OpenClassroomsAPI user data from the WP database.
Static Public Member Functions
static test ()
static reset ()
static httpRequest ($request)
Encasulates a HTTP GET or POST request using curl.
static httpRedirect ($url)
Encapsulates a HTTP redirection.
static getCurrentURL ()
Gets the current HTTP URL.
Detailed Description
Defines the functionnalities to acces to the OpenClassroooms API.
Usage:
 global $OpenClassroomsAPI;
 $data = $OpenClassroomsAPI->getUserLearningActivity();
The only routine to call is getUserLearningActivity() lower layer's call are transparent to the application layer
Code implementation: The code is organized in four layers:
OpenClassrooms user data retrieval
getUserLearningActivity()
OAuth2 token request method:
getAccessToken() encapsultates the OAuth2 protocol
Generic HTTP request and redirection methods:
httpRequest() httpRedirect() and getCurrentURL()
Wordpress dependent methods and error management
_construct() to hook the do_token_request() method
userData() for remanent user data management,
getAuth() secure local authentification parameters retrieval.
errorPage() user level error page if the syndication fails.
reportLog() to report an error in the log system.
OAuth2 parameters registration:
A .httpkeys PHP file must be present in the same directory as this source file (and never added to the git or svn !!!).
It must contains the information in an array of the form <php $httpkeys = array(
'OAuth2/client_id' => ..., // The OAuth2 client ID
'OAuth2/basic_auth' => ..., // The OAuth2 login:passwd basic auth
'OAuth2/redirect_uri' => ..., // The OAuth2 rediect URI
'OAuth2/help_url' => ..., // The user help url if the syndication fails
'OAuth2/log_email' => ..., // The mail to send error logs, in any (optional)); ?>
See also
https://github.com/vthierry/OpenClassroomsAPI for download
README.md and LICENCE for meta information
http://docs.openclassrooms.apiary.io/# for OpenClassrooms documentation
Definition at line 40 of file OpenClassroomsAPI.php.
Member Function Documentation
OpenClassroomsAPI::clearAccessToken ()
Clears the OAuth2 data in order to restart an authentification.
Definition at line 178 of file OpenClassroomsAPI.php.
References userData().
OpenClassroomsAPI::do_token_request ($request)
Implements the hook to manage redirection URL during OAuth2 token request.
Parameters
$request The global $_REQUEST parameter.
Definition at line 185 of file OpenClassroomsAPI.php.
References userData().
OpenClassroomsAPI::getAccessToken ()
Encapsulates a OAuth2 token request.
This method automatically detects if an access token exists, has to be refreshed, or if an authentification code has to be granted.
Returns
The "Authorization: Bearer " access token on succes; otherwise redirects to a user error page if it fails.
Definition at line 133 of file OpenClassroomsAPI.php.
References userData().
Referenced by getUserLearningActivity().
static OpenClassroomsAPI::getCurrentURL () static
Gets the current HTTP URL.
Definition at line 353 of file OpenClassroomsAPI.php.
OpenClassroomsAPI::getUserLearningActivity ($update = true, $as_string = false)
Gets the OpenClassroooms user learning activity for the registered courses.
Parameters
$update If true, request on https://api.openclassrooms.com the user_public_profile, user_followed_courses and related table-of-content to bluid the user-learning-activity. If false, simply returns the last stored value.
$as_string If true, returns the data as JSON string, else as a PHP array.
Returns
the userData user_learning_activity field or false if the operation fails. See usedData() for details.
Definition at line 64 of file OpenClassroomsAPI.php.
References getAccessToken(), and userData().
static OpenClassroomsAPI::httpRedirect ($url) static
Encapsulates a HTTP redirection.
The methods output javascript to replace the location and not header("Location : $url") because some HTML may have previously output.
Parameters
$url The redirection URL.
Definition at line 345 of file OpenClassroomsAPI.php.
static OpenClassroomsAPI::httpRequest ($request) static
Encasulates a HTTP GET or POST request using curl.
The method manages responses with partial content.
Parameters
$request An array with the following input fields:
url : The required URL to request,
header : An optional array of strings with the different header lines,
basic-auth : The optional $username.":".$password of the basic auth, if any,
post : If set, defines a post request and provides the post body. This sets header the Content-Length field.
with-range : If true performs several request in order to complete a partial range answer (i.e. code 206).
In that case the returned header is the 1st request header and the body is an array with all collected bodies.
Returns
An array with the following output fields:
code : The HTTP response status code (e.g., code 200 if ok),
request : The request, for tracing/debugging purpose,
header : An associative array with the response header as key => value,
With a code 206 the Content-range field is parsed as an array with the start-index, stop-index, and total-length.
body : The response body, if any. It is parsed as a JSON structure, if possible.
error : A string with an error message, or false if no error.
See also
http://php.net/manual/fr/ref.curl.php
Definition at line 243 of file OpenClassroomsAPI.php.
static OpenClassroomsAPI::reset () static
Definition at line 48 of file OpenClassroomsAPI.php.
References $OpenClassroomsAPI.
static OpenClassroomsAPI::test () static
Definition at line 43 of file OpenClassroomsAPI.php.
References $OpenClassroomsAPI.
OpenClassroomsAPI::userData ($name, $value = false, $clear = false)
Gets/Sets the OpenClassroomsAPI user data from the WP database.
This method must be overwitten for a non wordpress implementation.
This method returns the previously registered value, the getUserLearningActivity() method updates the data.
Parameters
$name The parameter name. Registered names are:
Registered by the getUserLearningActivity() method
user_id : The OC client ID;
user_public_profile : The OC user public profile.
See also
http://docs.openclassrooms.apiary.io/#reference/users/current-user/me
user_learning_activity : The OC user learning activity.
It is defined by the get-followed-courses-with-user-information,
With each course table-of-content with user information
See also
http://docs.openclassrooms.apiary.io/#reference/learning-activity/courses-followed-by-a-user/get-followed-courses-with-user-information
See also
http://docs.openclassrooms.apiary.io/#reference/learning-activity/table-of-content-with-user-information/get-table-of-content-with-user-information
Registered by the getAccessToken() method
code, state, access_token, access_token_expires_at, refresh_token, last_authentification : For OAuth2 management.
Parameters
$value The parameter value if to be set.
$clear If the $value is false and $clear is true, remove the value.
Returns
The parameter values.
Definition at line 382 of file OpenClassroomsAPI.php.
Referenced by clearAccessToken(), do_token_request(), getAccessToken(), and getUserLearningActivity().
The documentation for this class was generated from the following file:
OpenClassroomsAPI.php
Class'Code middleware (version of 2016-12-04 at 18:20:12)